name: sf_env
channels:
- snowflake
dependencies:
- pandas=2.2.3    ## This is supported by default
- streamlit
- snowflake-snowpark-python 
- seaborn=0.13.2
- scikit-learn=1.3.0
- pydeck=0.8.0
- matplotlib=3.7.2
